/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.manipulacaodestrings;

import javax.swing.JOptionPane;

/**
 *
 * @author Wanderson
 */
public class FormPrincipal extends javax.swing.JFrame {

    Gerencia gerencia;
    String operacao;

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        TFdigiteChave.setVisible(false);
        JBenviar.setVisible(false);
        gerencia = new Gerencia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JCoperacoes = new javax.swing.JComboBox<>();
        TFDigitePalavra = new javax.swing.JTextField();
        TFdigiteChave = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        TFresultado = new javax.swing.JTextField();
        JBenviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JCoperacoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vogais", "Inverter", "Tamanho", "Palíndromo", "Consoantes", "Criptografar", "Descriptografar" }));
        JCoperacoes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JCoperacoesFocusGained(evt);
            }
        });
        JCoperacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCoperacoesActionPerformed(evt);
            }
        });

        TFDigitePalavra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFDigitePalavra.setText("Digite a palavra");

        TFdigiteChave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFdigiteChave.setText("Digite uma chave de 1 digito");
        TFdigiteChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFdigiteChaveActionPerformed(evt);
            }
        });

        TFresultado.setEditable(false);
        TFresultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFresultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFresultado.setToolTipText("");

        JBenviar.setText("Enviar");
        JBenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBenviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TFDigitePalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCoperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFdigiteChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TFDigitePalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCoperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFdigiteChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBenviar)))
                    .addComponent(TFresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCoperacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCoperacoesActionPerformed
        operacao = JCoperacoes.getSelectedItem().toString();
        gerencia.setPalavra(TFDigitePalavra.getText());

        switch (operacao) {

            case "Inverter" ->
                TFresultado.setText(gerencia.inverter());
            case "Tamanho" ->
                TFresultado.setText(String.valueOf(gerencia.getPalavra().length()));
            case "Palíndromo" ->
                TFresultado.setText(gerencia.palindromo());
            case "Vogais" ->
                TFresultado.setText(gerencia.vogais());
            case "Consoantes" ->
                TFresultado.setText(gerencia.consoantes());
            case "Criptografar" -> {
                TFdigiteChave.setVisible(true);
                JBenviar.setVisible(true);
            }
            case "Descriptografar" -> {
                TFdigiteChave.setVisible(true);
                JBenviar.setVisible(true);
            }
        }
        ;
    }//GEN-LAST:event_JCoperacoesActionPerformed

    private void JBenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBenviarActionPerformed
        operacao = JCoperacoes.getSelectedItem().toString();
        if (!TFdigiteChave.equals("")) {
            gerencia.setChave(Integer.parseInt(TFdigiteChave.getText()));
            if ("Criptografar".equals(operacao)) {
                TFresultado.setText(gerencia.criptografar());
            } else {
                TFresultado.setText(gerencia.descriptografar());
            }
        } else
            JOptionPane.showMessageDialog(null, "Informe uma chave para continuar!");
    }//GEN-LAST:event_JBenviarActionPerformed

    private void TFdigiteChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFdigiteChaveActionPerformed
        TFdigiteChave.setText("");    }//GEN-LAST:event_TFdigiteChaveActionPerformed

    private void JCoperacoesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCoperacoesFocusGained
        operacao = JCoperacoes.getSelectedItem().toString();

    }//GEN-LAST:event_JCoperacoesFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBenviar;
    private javax.swing.JComboBox<String> JCoperacoes;
    private javax.swing.JTextField TFDigitePalavra;
    private javax.swing.JTextField TFdigiteChave;
    private javax.swing.JTextField TFresultado;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
